# -*- coding: utf-8 -*-
"""Without_converting_into_csv_Assignment Submission_for_Project_Officer (Hydrology)_muskingum routing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXaxh_U0fnaljoWCMg5MXkngiPgWeyAC

Import Libraries
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

"""I= inflow (m3/s),
Q= outflow(m3/s),
K= Storage time constant = 12 hour,
X= Weighing factor = 0.5,
Delta-T= 6 hour,
Time in Hour

Import Dataset
"""

I= np.loadtxt('test_routing.txt', skiprows=1, delimiter=',', dtype='int')
I

"""Preparing Dataset and Visualizing:"""

Time=np.empty(10)
Time[0]= 0
for i in range(1,10):
  Time[i] = 6 + Time[i-1]

plt.plot(Time,I,label='Inflows(m3/s)')
plt.title("Inflow Hydrograph")
plt.xlabel('Time(hr)')
plt.ylabel('Flow (cumec)')
plt.grid(visible = True, axis = 'y',  alpha = 0.6)
plt.legend()
plt.tight_layout()
plt.show()

"""Calculating C1,C2,C3:"""

K=12
X=0.5
delT=6
D = 2*K*(1-X)+ delT
# D
C1= (-(2*K*X)+ delT)/D
# C1
C2= ((2*K*X)+ delT)/D
# C2
C3= ((2*K*(1-X))- delT)/D
# C3

#check:
Z= C1+C2+C3
Z

"""Calculation Outflow,Q (m3/s): Outflow Equation: Qj+1 = C1IJ+1 + C2IJ + C3QJ"""

Q = np.empty(10)
Q[0] = 10
for i in range(1,10):
    Q[i] = C1*I[i] + C2*I[i-1] + C3*Q[i-1]

Q

"""Visualizing Inflow VS Outflow"""

plt.plot(Time,I, '-*', label='Inflow (m3/s)',color='salmon')
plt.plot(Time,Q, '--s', label='Outflow (m3/s)', color='steelblue')
plt.title("Inflow vs Outflow Hydrograph",fontweight = 'semibold')
plt.xlabel('Time(hr)',fontweight = 'semibold')
plt.ylabel('Flow Rate (cumec)',fontweight = 'semibold')
plt.grid(visible = True, axis = 'y',  alpha = 0.6)
plt.legend()
plt.savefig("Inflow vs Outflow Hydrograph.png", dpi=150, bbox_inches='tight')
plt.show()